# This workflow is currently disabled. Move to .github/workflows/ to enable.
name: Docker Build

# Triggered when a new version tag is pushed
on:
  push:
    tags:
      - 'v*'

# Workflow will:
# 1. Build multi-platform Docker images
# 2. Push to GitHub Container Registry
# 3. Tag with version and latest
# 4. Implement caching for faster builds
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      - name: Login to Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

# Required permissions:
# - packages: write
# - contents: read
# Required secrets:
# - GITHUB_TOKEN: Automatically provided (needs packages:write permission) 